"""
Temporal offline evaluation.

WHAT IT DOES

  1. Picks a cutoff at the 80th percentile of the interaction timeline.
  2. Rewinds the entire SQL pipeline to that cutoff and rebuilds every
     materialized view, so no post cutoff event is visible to any feature,
     similarity score or ranking.
  3. Asks three strategies for top 10 lists: popularity, pure collaborative
     filtering, and the hybrid ranker.
  4. Scores those lists against what users actually bought after the cutoff.
  5. Restores production mode.

WHY THE REWIND IS THE WHOLE POINT

The tempting shortcut is to build the similarity matrix on all the data and
then hold out a random slice of purchases. It produces excellent numbers and
they mean nothing, because the matrix already encoded the held out purchases
when it was built. Rewinding `pipeline_state.as_of_timestamp` and refreshing is
the only way to be certain the recommender is being asked to predict rather
than to recall.

WHAT PYTHON IS DOING HERE

Arithmetic on lists that SQL produced, and nothing else. Every recommendation
is generated by a PostgreSQL function. Python receives ranked product ids and
turns them into precision, recall, hit rate and NDCG. It never scores, ranks or
filters a candidate.

The numbers are written to docs/evaluation_results.md and to
data/evaluation_results.json, which the dashboard reads.
"""

from __future__ import annotations

import json
import math
import time
from collections import defaultdict

from python.config import DATA_DIR, DOCS_DIR, EVAL
from python.db import connect

STRATEGIES = ["popularity", "collaborative", "hybrid"]
STRATEGY_LABELS = {
    "popularity": "Popularity baseline",
    "collaborative": "Collaborative filtering",
    "hybrid": "Hybrid SQL recommender",
}
MAX_K = 10


# ===========================================================================
# Metrics. Binary relevance: a product was bought after the cutoff, or it was not.
# ===========================================================================

def precision_at_k(recommended: list[int], truth: set[int], k: int) -> float:
    if k == 0:
        return 0.0
    return len(set(recommended[:k]) & truth) / k


def recall_at_k(recommended: list[int], truth: set[int], k: int) -> float:
    if not truth:
        return 0.0
    return len(set(recommended[:k]) & truth) / len(truth)


def hit_rate_at_k(recommended: list[int], truth: set[int], k: int) -> float:
    return 1.0 if set(recommended[:k]) & truth else 0.0


def ndcg_at_k(recommended: list[int], truth: set[int], k: int) -> float:
    """
    Normalised discounted cumulative gain.

    Position matters: a correct product at rank 1 is worth more than the same
    product at rank 10, because that is how people read a shelf. The ideal DCG
    is the score a perfect ranking would achieve given how many correct answers
    exist, which keeps the metric on 0 to 1 for users with one held out
    purchase and users with twenty alike.
    """
    if not truth:
        return 0.0
    dcg = sum(
        1.0 / math.log2(position + 2)
        for position, product_id in enumerate(recommended[:k])
        if product_id in truth
    )
    ideal = sum(1.0 / math.log2(i + 2) for i in range(min(len(truth), k)))
    return dcg / ideal if ideal else 0.0


# ===========================================================================
# Data access. One round trip per strategy, not one per user.
# ===========================================================================

SAMPLE_USERS_SQL = """
    SELECT user_id, user_tier, total_interactions, future_purchases
    FROM eval_candidate_users
    ORDER BY md5(user_id::TEXT)
    LIMIT %s
"""

RECOMMENDATIONS_SQL = """
    WITH sampled AS (
        SELECT user_id
        FROM eval_candidate_users
        ORDER BY md5(user_id::TEXT)
        LIMIT %(n_users)s
    )
    SELECT s.user_id, r.product_id, r.rank
    FROM sampled AS s
    CROSS JOIN LATERAL eval_strategy_recommendations(
        %(strategy)s, s.user_id, %(k)s
    ) AS r
    ORDER BY s.user_id, r.rank
"""

GROUND_TRUTH_SQL = """
    WITH sampled AS (
        SELECT user_id
        FROM eval_candidate_users
        ORDER BY md5(user_id::TEXT)
        LIMIT %(n_users)s
    )
    SELECT g.user_id, g.product_id
    FROM eval_ground_truth AS g
    JOIN sampled AS s ON s.user_id = g.user_id
"""


def run_evaluation() -> dict:
    started = time.perf_counter()
    results: dict = {}

    with connect(autocommit=True) as conn:
        production_cutoff = conn.execute(
            "SELECT MAX(interaction_timestamp) + INTERVAL '1 second' AS ts "
            "FROM user_interactions"
        ).fetchone()["ts"]

        cutoff = conn.execute(
            "SELECT evaluation_cutoff(%s::NUMERIC) AS cutoff", (EVAL.train_fraction,)
        ).fetchone()["cutoff"]

        print(f"Temporal split at {cutoff} ({EVAL.train_fraction:.0%} of the timeline)")
        print("Rewinding the pipeline and rebuilding the offline layer")

        rewind_started = time.perf_counter()
        conn.execute("SELECT set_pipeline_as_of(%s, 'evaluation')", (cutoff,))
        print(f"  rebuilt in {time.perf_counter() - rewind_started:.1f}s")

        try:
            split_stats = conn.execute(
                """
                SELECT
                    COUNT(*) FILTER (WHERE interaction_timestamp <  rec_as_of()) AS train_events,
                    COUNT(*) FILTER (WHERE interaction_timestamp >= rec_as_of()) AS test_events
                FROM user_interactions
                """
            ).fetchone()

            users = conn.execute(SAMPLE_USERS_SQL, (EVAL.n_eval_users,)).fetchall()
            user_tier = {row["user_id"]: row["user_tier"] for row in users}

            truth: dict[int, set[int]] = defaultdict(set)
            for row in conn.execute(
                GROUND_TRUTH_SQL, {"n_users": EVAL.n_eval_users}
            ).fetchall():
                truth[row["user_id"]].add(row["product_id"])

            print(
                f"  {len(users):,} evaluation users, "
                f"{sum(len(v) for v in truth.values()):,} held out purchases"
            )

            strategy_results = {}
            for strategy in STRATEGIES:
                step = time.perf_counter()
                recommended: dict[int, list[int]] = defaultdict(list)
                rows = conn.execute(
                    RECOMMENDATIONS_SQL,
                    {"n_users": EVAL.n_eval_users, "strategy": strategy, "k": MAX_K},
                ).fetchall()
                for row in rows:
                    recommended[row["user_id"]].append(row["product_id"])

                metrics = score_strategy(users, recommended, truth, user_tier)
                metrics["seconds"] = round(time.perf_counter() - step, 2)
                metrics["mean_latency_ms"] = round(
                    metrics["seconds"] * 1000 / max(len(users), 1), 2
                )

                coverage = conn.execute(
                    "SELECT * FROM eval_coverage_report(%s, 300, 10)", (strategy,)
                ).fetchone()
                metrics["catalogue_coverage"] = float(coverage["catalogue_coverage"])
                metrics["head_share"] = float(coverage["head_share"])
                metrics["distinct_products"] = int(coverage["distinct_products"])

                strategy_results[strategy] = metrics
                print(
                    f"  {STRATEGY_LABELS[strategy]:<26} "
                    f"{len(rows):>7,} rows for {len(recommended):>5,} users "
                    f"in {metrics['seconds']:.1f}s"
                )

            results = {
                "cutoff": str(cutoff),
                "train_fraction": EVAL.train_fraction,
                "train_events": int(split_stats["train_events"]),
                "test_events": int(split_stats["test_events"]),
                "n_users": len(users),
                "held_out_purchases": sum(len(v) for v in truth.values()),
                "strategies": strategy_results,
            }

        finally:
            print("Restoring production mode")
            conn.execute("SELECT set_pipeline_as_of(%s, 'production')", (production_cutoff,))

    results["elapsed_seconds"] = round(time.perf_counter() - started, 1)
    return results


def score_strategy(
    users: list[dict],
    recommended: dict[int, list[int]],
    truth: dict[int, set[int]],
    user_tier: dict[int, str],
) -> dict:
    totals: dict[str, list[float]] = defaultdict(list)
    by_tier: dict[str, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))

    for row in users:
        user_id = row["user_id"]
        recs = recommended.get(user_id, [])
        relevant = truth.get(user_id, set())
        if not relevant:
            continue

        tier = user_tier.get(user_id, "unknown")

        # A user the strategy returned nothing for is a failure, not an
        # exclusion. Scoring them as absent would let a strategy that serves
        # half the user base look identical to one that serves all of it.
        totals["served_rate"].append(1.0 if recs else 0.0)
        by_tier[tier]["served_rate"].append(1.0 if recs else 0.0)

        for k in EVAL.cutoffs:
            for name, value in (
                (f"precision_at_{k}", precision_at_k(recs, relevant, k)),
                (f"recall_at_{k}", recall_at_k(recs, relevant, k)),
                (f"hit_rate_at_{k}", hit_rate_at_k(recs, relevant, k)),
                (f"ndcg_at_{k}", ndcg_at_k(recs, relevant, k)),
            ):
                totals[name].append(value)
                by_tier[tier][name].append(value)

    metrics = {name: round(sum(values) / len(values), 4) for name, values in totals.items()}
    metrics["users_scored"] = len(totals[f"precision_at_{EVAL.cutoffs[0]}"])
    metrics["by_tier"] = {
        tier: {
            "users": len(values[f"precision_at_{EVAL.cutoffs[0]}"]),
            **{
                name: round(sum(v) / len(v), 4)
                for name, v in values.items()
            },
        }
        for tier, values in sorted(by_tier.items())
    }
    return metrics


# ===========================================================================
# Reporting
# ===========================================================================

METRIC_ORDER = [
    ("precision_at_5", "Precision@5"),
    ("precision_at_10", "Precision@10"),
    ("recall_at_5", "Recall@5"),
    ("recall_at_10", "Recall@10"),
    ("hit_rate_at_10", "Hit Rate@10"),
    ("ndcg_at_10", "NDCG@10"),
    ("served_rate", "Users served"),
]


def render_report(results: dict) -> str:
    lines: list[str] = []
    lines.append("# Evaluation results")
    lines.append("")
    lines.append(
        "Generated by `python -m python.evaluate`. Every number here comes from "
        "recommendations produced by PostgreSQL functions and scored in Python. "
        "Nothing is hand entered."
    )
    lines.append("")
    lines.append("## Split")
    lines.append("")
    lines.append("| Property | Value |")
    lines.append("| - | - |")
    lines.append(f"| Cutoff timestamp | {results['cutoff']} |")
    lines.append(f"| Training share of timeline | {results['train_fraction']:.0%} |")
    lines.append(f"| Events before cutoff | {results['train_events']:,} |")
    lines.append(f"| Events after cutoff | {results['test_events']:,} |")
    lines.append(f"| Users evaluated | {results['n_users']:,} |")
    lines.append(f"| Held out purchases | {results['held_out_purchases']:,} |")
    lines.append("")
    lines.append("## Accuracy")
    lines.append("")
    header = "| Metric | " + " | ".join(
        STRATEGY_LABELS[s] for s in STRATEGIES
    ) + " |"
    lines.append(header)
    lines.append("| - | " + " | ".join("-:" for _ in STRATEGIES) + " |")
    for key, label in METRIC_ORDER:
        row = [f"{results['strategies'][s][key]:.4f}" for s in STRATEGIES]
        lines.append(f"| {label} | " + " | ".join(row) + " |")
    lines.append("")
    lines.append("## Catalogue behaviour")
    lines.append("")
    lines.append(
        "| Property | " + " | ".join(STRATEGY_LABELS[s] for s in STRATEGIES) + " |"
    )
    lines.append("| - | " + " | ".join("-:" for _ in STRATEGIES) + " |")
    for key, label, fmt in [
        ("distinct_products", "Distinct products recommended", "{:,}"),
        ("catalogue_coverage", "Catalogue coverage", "{:.1%}"),
        ("head_share", "Share from the head of demand", "{:.1%}"),
        ("mean_latency_ms", "Mean latency per user (ms)", "{:.2f}"),
    ]:
        row = [fmt.format(results["strategies"][s][key]) for s in STRATEGIES]
        lines.append(f"| {label} | " + " | ".join(row) + " |")
    lines.append("")
    lines.append("## Hybrid recommender by user tier")
    lines.append("")
    lines.append(
        "| Tier | Users | Precision@10 | Recall@10 | Hit Rate@10 | NDCG@10 | Users served |"
    )
    lines.append("| - | -: | -: | -: | -: | -: | -: |")
    for tier, values in results["strategies"]["hybrid"]["by_tier"].items():
        lines.append(
            f"| {tier} | {values['users']:,} | {values['precision_at_10']:.4f} | "
            f"{values['recall_at_10']:.4f} | {values['hit_rate_at_10']:.4f} | "
            f"{values['ndcg_at_10']:.4f} | {values['served_rate']:.4f} |"
        )
    lines.append("")
    lines.append("## Cold start: users served by each strategy")
    lines.append("")
    lines.append("| Tier | " + " | ".join(STRATEGY_LABELS[s] for s in STRATEGIES) + " |")
    lines.append("| - | " + " | ".join("-:" for _ in STRATEGIES) + " |")
    tiers = results["strategies"]["hybrid"]["by_tier"].keys()
    for tier in tiers:
        row = [
            f"{results['strategies'][s]['by_tier'].get(tier, {}).get('served_rate', 0.0):.4f}"
            for s in STRATEGIES
        ]
        lines.append(f"| {tier} | " + " | ".join(row) + " |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    results = run_evaluation()

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    report = render_report(results)
    (DOCS_DIR / "evaluation_results.md").write_text(report, encoding="utf-8")
    (DATA_DIR / "evaluation_results.json").write_text(
        json.dumps(results, indent=2), encoding="utf-8"
    )

    print()
    print(report)
    print(f"Total elapsed {results['elapsed_seconds']}s")


if __name__ == "__main__":
    main()
